/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BaseBtn: typeof import('./src/components/UI/buttons/BaseBtn.vue')['default']
    BaseIcon: typeof import('./src/components/UI/icons/BaseIcon.vue')['default']
    BaseInput: typeof import('./src/components/UI/buttons/BaseInput.vue')['default']
    Button: typeof import('primevue/button')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
